# ------------------------------------------------------- #
# Note: this file originates in template-action-composite #
# ------------------------------------------------------- #

services:
  # ---- mega-linter ---- #
  lint:
    image: oxsecurity/megalinter-documentation:v7.2.1
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- readme generator ---- #
  readme:
    image: pandoc/minimal:2.19
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
