version: '3.8'

services:
  # ---- super-linter ---- #
  super-linter:
    image: github/super-linter:v3
    volumes:
      - ./:/tmp/lint
    environment:
      RUN_LOCAL: 'true'
      LOG_LEVEL: 'ERROR'
      MULTI_STATUS: 'false'
      VALIDATE_SHELL_SHFMT: 'false'
      VALIDATE_JSCPD: 'false'

  # ---- readme generator ---- #
  readme:
    image: pandoc/core:2.11.4
    volumes:
      - ./:/data
    command: >-
      --metadata-file=colophon.yml
      --template=docs/README.template
      --output=README.md
      --from=gfm
      --to=gfm
      --fail-if-warnings
      --wrap=preserve
      --reference-links
      docs/README.md
